name: base docker build

on:
  workflow_call:
    inputs:
      dockerfile-path:
        required: true
        type: string
        description: The path to the dockerfile to use for the docker image
      image-tag:
        required: true
        type: string
        description: The image tag to use for the docker image
    secrets:
      DOCKER_USERNAME:
        required: true
        description: The docker use name that logs in to Dockerhub
      DOCKER_TOKEN:
        required: true
        description: The docker token that logs in to Dockerhub

jobs:
  build-push:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:

      - name: Project checkout
        uses: actions/checkout@v3
        id: project_checkout

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        id: docker_login

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: ${{ inputs.dockerfile-path }}
          push: true
          tags: ${{ inputs.image-tag }}
        id: docker_build_push