name: Build and push docker image

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build:3.18.0
    uses: ./.github/workflows/base-docker-build-push.yaml
    with:
      dockerfile-path: ./3.18.0/Dockerfile
      image-tag      : ${{ vars.DOCKER_IMAGE_NAME }}:3.18.0
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN   : ${{ secrets.DOCKER_TOKEN }}