name: Build and push docker image

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  alpine:
    name: alpine-v3.18.2
    uses: ./.github/workflows/base-docker-workflow.yaml
    with:
      dockerfile-path: ./3.18.2/Dockerfile
      image-tags     : ${{ vars.DOCKER_IMAGE_NAME }}:3.18.2
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN   : ${{ secrets.DOCKER_TOKEN }}